[package]
name = "rust-ray-tracer"
version = "0.1.0"
authors = ["Will Fleming <wfleming77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
